[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.build]
cmds = [
    "pip install -r requirements.txt"
]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10