[build]
builder = "nixpacks"

[build.nixpacksPlan]
providers = ["python"]

[build.nixpacksPlan.phases.build]
cmds = [
    "pip install -r requirements.txt",
    "python manage.py collectstatic --noinput"
]

[build.nixpacksPlan.phases.deploy]
cmds = ["python manage.py migrate"]

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10