# Generated by Django 5.2.3 on 2025-07-23 05:56

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Підтип робіт')),
                ('has_equipment', models.BooleanField(default=False, verbose_name='Потребує обладнання')),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Тип робіт')),
            ],
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
            ],
            options={
                'verbose_name': 'Адміністратор підрозділу',
                'verbose_name_plural': 'Адміністратори підрозділів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TenderUser',
            fields=[
            ],
            options={
                'verbose_name': 'Переможець тендеру',
                'verbose_name_plural': 'Переможці тендерів',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Обладнання')),
                ('subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='users.worksubtype')),
            ],
        ),
        migrations.AddField(
            model_name='worksubtype',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtypes', to='users.worktype'),
        ),
        migrations.DeleteModel(
            name='AdminDepartmentAccess',
        ),
    ]
