# Generated by Django 5.1 on 2025-08-20 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_worksubtype_worktype_staffuser_tenderuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид інструменту')),
                ('required_documents', models.JSONField(default=list, verbose_name='Необхідні документи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Тип інструменту',
                'verbose_name_plural': 'Типи інструментів',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип техніки')),
                ('required_documents', models.JSONField(default=list, verbose_name='Необхідні документи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Тип техніки',
                'verbose_name_plural': 'Типи техніки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('photo', models.FileField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фото')),
                ('medical_exam_date', models.DateField(verbose_name='Дата закінчення медогляду')),
                ('organization_name', models.CharField(blank=True, max_length=255, verbose_name='Назва організації')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Посада/професія')),
                ('qualification_certificate', models.FileField(blank=True, null=True, upload_to='employees/qualifications/', verbose_name='Кваліфікаційне посвідчення')),
                ('qualification_issue_date', models.DateField(verbose_name='Дата видачі кваліфікації')),
                ('safety_training_certificate', models.FileField(blank=True, null=True, upload_to='employees/safety/', verbose_name='Посвідчення про навчання з ОП')),
                ('safety_training_date', models.DateField(verbose_name='Дата закінчення дії ОП')),
                ('special_training_certificate', models.FileField(blank=True, null=True, upload_to='employees/special/', verbose_name='Посвідчення про спеціальне навчання')),
                ('special_training_date', models.DateField(blank=True, null=True, verbose_name='Дата закінчення спецнавчання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Співробітник',
                'verbose_name_plural': 'Співробітники',
                'ordering': ['user', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(blank=True, max_length=255, verbose_name='Інший тип (якщо не знайшли)')),
                ('documents', models.JSONField(default=dict, verbose_name='Документи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('instrument_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.instrumenttype', verbose_name='Тип інструменту')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruments', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Інструмент',
                'verbose_name_plural': 'Інструменти',
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPPE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.JSONField(default=list, verbose_name='Документи ЗІЗ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ppe', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'ЗІЗ',
                'verbose_name_plural': 'ЗІЗ',
            },
        ),
        migrations.CreateModel(
            name='UserSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specification_type', models.TextField(blank=True, verbose_name='Тип робіт за специфікацією')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Специфікація робіт',
                'verbose_name_plural': 'Специфікації робіт',
            },
        ),
        migrations.CreateModel(
            name='UserTechnic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_type', models.CharField(blank=True, max_length=255, verbose_name='Інший тип (якщо не знайшли)')),
                ('documents', models.JSONField(default=dict, verbose_name='Документи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('technic_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.technictype', verbose_name='Тип техніки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technics', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Техніка',
                'verbose_name_plural': 'Техніка',
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('responsible_person', 'Про призначення відповідальних за організацію і безпечне виконання робіт підвищеної небезпеки'), ('fire_safety', "Відповідальний за належний стан пожежної безпеки на об'єкті виконання робіт"), ('eco_safety', "Відповідальний за належний стан екологічної безпеки на об'єкті виконання робіт"), ('certificates_protocols', 'Копії посвідчень та протоколів навчання і перевірки знань правил з охорони праці відповідальних осіб'), ('worker_training', 'Копії посвідчень та протоколів навчання і перевірки знань правил з охорони праці та навчання безпечним методам роботи працівників'), ('medical_conclusions', 'Медичні заключення про допуск до виконання робіт за зазначеними професіями')], max_length=50, verbose_name='Тип наказу')),
                ('documents', models.JSONField(default=list, verbose_name='Документи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Наказ',
                'verbose_name_plural': 'Накази',
                'ordering': ['user', 'order_type'],
                'unique_together': {('user', 'order_type')},
            },
        ),
        migrations.CreateModel(
            name='UserWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiry_date', models.DateField(verbose_name='Дата завершення дії дозволу')),
                ('permit_file', models.FileField(blank=True, null=True, upload_to='permits/', verbose_name='Файл дозволу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('work_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worksubtype', verbose_name='Підтип роботи')),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.worktype', verbose_name='Тип роботи')),
            ],
            options={
                'verbose_name': 'Робота користувача',
                'verbose_name_plural': 'Роботи користувачів',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'work_sub_type')},
            },
        ),
    ]
