# Generated by Django 5.1 on 2025-08-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_user_data_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userorder',
            unique_together=set(),
        ),
    ]
