# Generated by Django 5.1 on 2025-08-22 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userorder_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useremployee',
            options={'ordering': ['name'], 'verbose_name': 'Співробітник', 'verbose_name_plural': 'Співробітники'},
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='medical_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата медогляду'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='name',
            field=models.CharField(max_length=255, verbose_name='ПІБ співробітника'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Назва організації що проводила медогляд'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='employees/photos/', verbose_name='Фото співробітника'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='position',
            field=models.CharField(blank=True, max_length=255, verbose_name='Посада'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employees/qualifications/', verbose_name='Посвідчення кваліфікації'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='qualification_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата видачі посвідчення'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='safety_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employees/safety/', verbose_name='Посвідчення з охорони праці'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='safety_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата навчання з охорони праці'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='special_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to='employees/special/', verbose_name='Посвідчення спеціального навчання'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='special_training_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата спеціального навчання'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userspecification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='specification', to=settings.AUTH_USER_MODEL),
        ),
    ]
