# Generated by Django 5.1 on 2025-08-22 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fix_useremployee_and_add_userspecification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('view_own_department_users', 'Can view users from own department'), ('change_own_department_users', 'Can change users from own department'), ('approve_tender_users', 'Can approve tender winners'), ('decline_tender_users', 'Can decline tender winners')], 'verbose_name': 'Користувач', 'verbose_name_plural': 'Користувачі'},
        ),
    ]
