# Generated by Django 5.2.4 on 2025-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userorder',
            options={'ordering': ['user', 'order_type', '-created_at'], 'verbose_name': 'Наказ', 'verbose_name_plural': 'Накази'},
        ),
        migrations.AddField(
            model_name='userorder',
            name='custom_title',
            field=models.CharField(blank=True, help_text='Заповнюється тільки для типу "Інші накази"', max_length=500, verbose_name='Назва кастомного наказу'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.TextField(verbose_name='Обладнання'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_type',
            field=models.CharField(choices=[('responsible_person', 'Про призначення відповідальних за організацію і безпечне виконання робіт підвищеної небезпеки'), ('fire_safety', "Відповідальний за належний стан пожежної безпеки на об'єкті виконання робіт"), ('eco_safety', "Відповідальний за належний стан екологічної безпеки на об'єкті виконання робіт"), ('certificates_protocols', 'Копії посвідчень та протоколів навчання і перевірки знань правил з охорони праці відповідальних осіб'), ('worker_training', 'Копії посвідчень та протоколів навчання і перевірки знань правил з охорони праці та навчання безпечним методам роботи працівників'), ('medical_conclusions', 'Медичні заключення про допуск до виконання робіт за зазначеними професіями'), ('custom', 'Інші накази')], max_length=50, verbose_name='Тип наказу'),
        ),
        migrations.AlterField(
            model_name='worksubtype',
            name='name',
            field=models.TextField(verbose_name='Підтип робіт'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.TextField(verbose_name='Тип робіт'),
        ),
    ]
