# Generated by Django 5.2.4 on 2025-09-04 07:19

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userorder_options_userorder_custom_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file_value',
            field=models.FileField(blank=True, upload_to=users.models.user_document_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_employee_photo_path, verbose_name='Фото співробітника'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='qualification_certificate',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_employee_qualification_path, verbose_name='Посвідчення кваліфікації'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='safety_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_employee_safety_path, verbose_name='Посвідчення з охорони праці'),
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='special_training_certificate',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_employee_special_path, verbose_name='Посвідчення спеціального навчання'),
        ),
        migrations.AlterField(
            model_name='userwork',
            name='permit_file',
            field=models.FileField(blank=True, null=True, upload_to=users.models.user_work_permit_path, verbose_name='Файл дозволу'),
        ),
    ]
