# Generated by Django 5.2.4 on 2025-09-24 16:32

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_update_file_upload_paths'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True)),
                ('permit_type', models.CharField(choices=[('employee', 'Працівник'), ('technic', 'Техніка')], max_length=20)),
                ('pdf_file', models.FileField(upload_to=users.models.user_permit_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permits', to=settings.AUTH_USER_MODEL)),
                ('employee', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='users.useremployee')),
                ('technic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permit', to='users.usertechnic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Перепустка',
                'verbose_name_plural': 'Перепустки',
            },
        ),
    ]
