# Generated by Django 5.2.4 on 2025-10-03 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_permit'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertechnic',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Реєстраційний номер'),
        ),
    ]
