# Generated by Django 5.2.4 on 2025-10-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usertechnic_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('in_progress', 'Допущений'), ('accepted', 'Підтверджений'), ('declined', 'Відхилений'), ('blocked', 'Заблокований')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='usertechnic',
            name='registration_number',
            field=models.CharField(default='', max_length=50, verbose_name='Державний реєстраційний номер'),
            preserve_default=False,
        ),
    ]
