# Generated by Django 5.2.4 on 2025-10-08 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_make_registration_number_optional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useremployee',
            old_name='qualification_issue_date',
            new_name='qualification_expiry_date',
        ),
        migrations.AlterField(
            model_name='useremployee',
            name='qualification_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Термін дії кваліфікаційного посвідчення'),
        ),
    ]
